- hosts: webservers
  become: true
  tasks:
    - name: perform apt-get update
      apt:
        update_cache: yes
    - name: install java
      apt:
        name: default-jdk
        state: latest
    - name: Copy Artifact to host
      copy:
        src: "{{ item }}"
        dest: ~/myapp.jar
      with_fileglob:
        - "/home/sourav10mohanty/azagent/_work/r1/a/_sourav_99.customer-application/Manifests/target/*.jar"
    - name: Start java application
      shell: nohup java -jar ~/myapp.jar &