apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-application
  labels:
    app: customer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      imagePullSecrets:
      - name: docker-registry-key
      containers:
      - name: customer-app-container
        image: souravcoder99/customer-dockerapp:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 2000Mi
---
apiVersion: v1
kind: Service
metadata:
    name: customer-app-service
spec:
    type: LoadBalancer
    ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080
       nodePort: 30000
    selector:
       app: customer-app